# <!-- Powered by BMAD™ Core -->
markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/project/prd.md
  prdVersion: v4
  prdSharded: false
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture/README.md
  architectureVersion: v4
  architectureSharded: false
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/developer/technical-development-guide.md
  - docs/developer/project-structure.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
